version: '3'
services:
  db:
    image: postgres
    environment:
       POSTGRES_PASSWORD: admin
       POSTGRES_USER: postgres
       POSTGRES_DB: e_attestation
  app:
    image: e_attestation
    ports:
      - 13000:3000
      

        

